import { Chain, ChainCatalogData } from './types.js';

export const STATIC_CHAIN_CATALOG: Record<Chain, ChainCatalogData> = {
  migros: {
    products: [
      {
        id: 'migros-milk-1l',
        chain: 'migros',
        name: 'Organic Whole Milk',
        brand: 'M-Budget',
        category: 'dairy',
        size: '1l',
        price: { current: 1.85, unit: { value: 1, per: 'l' } },
        tags: ['organic', 'vegetarian'],
        allergens: ['milk'],
      },
      {
        id: 'migros-pasta-500g',
        chain: 'migros',
        name: 'Wholegrain Pasta',
        brand: 'M-Classic',
        category: 'pantry',
        size: '500g',
        price: { current: 1.7, unit: { value: 0.5, per: 'kg' } },
        tags: ['vegan', 'vegetarian'],
        allergens: ['gluten'],
      },
    ],
    stores: [
      {
        id: 'migros-zurich-1',
        chain: 'migros',
        name: 'Migros Zürich HB',
        address: 'ShopVille, Bahnhofplatz, 8001 Zürich',
        location: { latitude: 47.3782, longitude: 8.5402 },
        openingHours: 'Mon-Sat 07:00-22:00',
      },
    ],
    storeInventory: {
      'migros-zurich-1': ['migros-milk-1l'],
    },
  },
  coop: {
    products: [
      {
        id: 'coop-milk-1l',
        chain: 'coop',
        name: 'Bio Whole Milk',
        brand: 'Naturaplan',
        category: 'dairy',
        size: '1l',
        price: { current: 1.95, unit: { value: 1, per: 'l' } },
        tags: ['organic', 'vegetarian'],
        allergens: ['milk'],
      },
      {
        id: 'coop-rice-1kg',
        chain: 'coop',
        name: 'Basmati Rice',
        brand: 'Prix Garantie',
        category: 'pantry',
        size: '1kg',
        price: { current: 2.9, unit: { value: 1, per: 'kg' } },
        tags: ['vegan', 'gluten-free', 'vegetarian'],
      },
    ],
    stores: [
      {
        id: 'coop-basel-1',
        chain: 'coop',
        name: 'Coop Basel Central',
        address: 'Aeschenvorstadt 1, 4051 Basel',
        location: { latitude: 47.5539, longitude: 7.5907 },
        openingHours: 'Mon-Sat 08:00-20:00',
      },
    ],
  },
  aldi: {
    products: [
      {
        id: 'aldi-oats-1kg',
        chain: 'aldi',
        name: 'Rolled Oats',
        brand: 'Golden Bridge',
        category: 'breakfast',
        size: '1kg',
        price: { current: 1.8, unit: { value: 1, per: 'kg' } },
        tags: ['vegan', 'vegetarian'],
        allergens: ['gluten'],
      },
      {
        id: 'aldi-apple-1kg',
        chain: 'aldi',
        name: 'Apples Gala',
        brand: 'Fresh',
        category: 'produce',
        size: '1kg',
        price: { current: 2.2, unit: { value: 1, per: 'kg' } },
        tags: ['vegan', 'gluten-free', 'vegetarian'],
      },
    ],
    stores: [
      {
        id: 'aldi-bern-1',
        chain: 'aldi',
        name: 'ALDI Bern Bahnhof',
        address: 'Bahnhofstrasse 10, 3011 Bern',
        location: { latitude: 46.948, longitude: 7.4391 },
        openingHours: 'Mon-Sat 07:30-20:00',
      },
    ],
  },
  denner: {
    products: [
      {
        id: 'denner-eggs-10',
        chain: 'denner',
        name: 'Free Range Eggs',
        brand: 'Denner',
        category: 'dairy',
        size: '10 pieces',
        price: { current: 3.95, unit: { value: 10, per: 'piece' } },
        tags: ['vegetarian'],
        allergens: ['egg'],
      },
      {
        id: 'denner-pasta-500g',
        chain: 'denner',
        name: 'Penne Rigate',
        brand: 'Denner',
        category: 'pantry',
        size: '500g',
        price: { current: 1.2, unit: { value: 0.5, per: 'kg' } },
        tags: ['vegan', 'vegetarian'],
        allergens: ['gluten'],
      },
    ],
    stores: [
      {
        id: 'denner-luzern-1',
        chain: 'denner',
        name: 'Denner Luzern Zentrum',
        address: 'Pilatusstrasse 5, 6003 Luzern',
        location: { latitude: 47.0496, longitude: 8.3072 },
        openingHours: 'Mon-Sat 08:00-20:00',
      },
    ],
  },
  lidl: {
    products: [
      {
        id: 'lidl-yogurt-500g',
        chain: 'lidl',
        name: 'Greek Yogurt',
        brand: 'Milbona',
        category: 'dairy',
        size: '500g',
        price: { current: 2.4, unit: { value: 0.5, per: 'kg' } },
        tags: ['vegetarian'],
        allergens: ['milk'],
      },
      {
        id: 'lidl-chickpeas-400g',
        chain: 'lidl',
        name: 'Chickpeas',
        brand: 'Freshona',
        category: 'pantry',
        size: '400g',
        price: { current: 1.1, unit: { value: 0.4, per: 'kg' } },
        tags: ['vegan', 'gluten-free', 'vegetarian'],
      },
    ],
    stores: [
      {
        id: 'lidl-geneva-1',
        chain: 'lidl',
        name: 'Lidl Genève Plainpalais',
        address: 'Rue de Carouge 40, 1205 Genève',
        location: { latitude: 46.1964, longitude: 6.1432 },
        openingHours: 'Mon-Sat 08:00-20:30',
      },
    ],
  },
  farmy: {
    products: [
      {
        id: 'farmy-bread-600g',
        chain: 'farmy',
        name: 'Sourdough Bread',
        brand: 'Farmy Bakery',
        category: 'bakery',
        size: '600g',
        price: { current: 4.9, unit: { value: 0.6, per: 'kg' } },
        tags: ['vegetarian', 'organic'],
        allergens: ['gluten'],
      },
      {
        id: 'farmy-spinach-250g',
        chain: 'farmy',
        name: 'Baby Spinach',
        brand: 'Farmy Fresh',
        category: 'produce',
        size: '250g',
        price: { current: 3.5, unit: { value: 0.25, per: 'kg' } },
        tags: ['vegan', 'gluten-free', 'organic', 'vegetarian'],
      },
    ],
    stores: [
      {
        id: 'farmy-zurich-warehouse',
        chain: 'farmy',
        name: 'Farmy Zürich Hub',
        address: 'Pfingstweidstrasse 101, 8005 Zürich',
        location: { latitude: 47.3893, longitude: 8.5157 },
        openingHours: 'Mon-Sat 07:00-20:00',
      },
    ],
  },
  volg: {
    products: [
      {
        id: 'volg-cheese-200g',
        chain: 'volg',
        name: 'Mountain Cheese',
        brand: 'Volg',
        category: 'dairy',
        size: '200g',
        price: { current: 3.7, unit: { value: 0.2, per: 'kg' } },
        tags: ['vegetarian'],
        allergens: ['milk'],
      },
      {
        id: 'volg-potatoes-1kg',
        chain: 'volg',
        name: 'Swiss Potatoes',
        brand: 'Volg Fresh',
        category: 'produce',
        size: '1kg',
        price: { current: 2.8, unit: { value: 1, per: 'kg' } },
        tags: ['vegan', 'gluten-free', 'vegetarian'],
      },
    ],
    stores: [
      {
        id: 'volg-stgallen-1',
        chain: 'volg',
        name: 'Volg St. Gallen',
        address: 'Rosenbergstrasse 2, 9000 St. Gallen',
        location: { latitude: 47.4245, longitude: 9.3767 },
        openingHours: 'Mon-Sat 07:30-19:00',
      },
    ],
  },
  ottos: {
    products: [
      {
        id: 'ottos-detergent-1l',
        chain: 'ottos',
        name: 'Laundry Detergent',
        brand: "Otto's Home",
        category: 'household',
        size: '1l',
        price: { current: 5.2, unit: { value: 1, per: 'l' } },
        tags: ['budget'],
      },
      {
        id: 'ottos-pasta-500g',
        chain: 'ottos',
        name: 'Spaghetti',
        brand: "Otto's",
        category: 'pantry',
        size: '500g',
        price: { current: 1, unit: { value: 0.5, per: 'kg' } },
        tags: ['vegan', 'vegetarian'],
        allergens: ['gluten'],
      },
    ],
    stores: [
      {
        id: 'ottos-zug-1',
        chain: 'ottos',
        name: "Otto's Zug",
        address: 'Baarerstrasse 20, 6300 Zug',
        location: { latitude: 47.174, longitude: 8.5155 },
        openingHours: 'Mon-Sat 09:00-19:00',
      },
    ],
  },
};
